### ISSUE TITLE
Feature request: Edge profiles

### ISSUE THREAD

**Issue by HerrStinson** [jorgenpt/bichrome#15]
It would be nice to utilize the "browser profiles" feature which can be already be configured for Chrome for Edge as well. Edge follows the same --profile-directory approach as Chrome does.

@jorgenpt love this tool to death, thx!

Thx and BR - HerrStinson

**Comment by jorgenpt** [comment]
Glad to hear you like it! I'll take a stab at this at some point soon, I have another little item I want to try implementing while I'm at it. No guarantee on the timing. :)

**Comment by jorgenpt** [comment]
@HerrStinson I've published a new version that should implement this, you can find it [on the releases page](https://github.com/jorgenpt/bichrome/releases/tag/v0.6.0). Let me know if you encounter any issue!

Note that the Windows executables are no longer code signed because my certificate ran out and I haven't renewed it (it's $27/year, and I don't use it for anything other than bichrome), so I'm not sure if it'll prompt you about that when you first start the new version.

**Comment by HerrStinson** [comment]
@jorgenpt works like a charm and is very much appreciated, thanks! If you have a link to buy you a coffee or a beer let me know, I will gladly do so!

**Comment by jorgenpt** [comment]
That's kind of you! I set up a ko-fi, figured why not. :) https://ko-fi.com/jorgenpt
