### ISSUE TITLE
Pattern matching: url instead of domain?

### ISSUE THREAD

**Issue by HerrStinson** [jorgenpt/bichrome#18]
Hi @jorgenpt,

I would like to to open urls outlook.office365.com/ and outlook.office365.com/ecp/ in two different browsers. Currently the matching seems to only work on domain basis, outlook.office365.com/ecp/ is not picked up as a match. Could matching possibly be extended to urls?

Thx and BR - HerrStinson

**Comment by jorgenpt** [comment]
@HerrStinson, the matching should work for paths as well as for domains. If you don't specify a path, it'll match any path, and it will pick the first profile that matches. In your example, you'd want something like this:

```json
    "profile_selection": [
        {
            "profile": "FirstBrowser",
            "pattern": "outlook.office365.com/ecp/*"
        },
        {
            "profile": "SecondBrowser",
            "pattern": "outlook.office365.com"
        }
    ]
```

The important things to note are:
 1. If you don't specify any pattern for the path (like the second example there), it implicitly matches any path (so `outlook.office365.com/*` and `outlook.office365.com` are the same thing)
 2. It uses the first profile in the list that matches the URL so the more permissive one should be **after** the more specific one
 3. You need to include a wildcard at the end of the path if you want to match any subpath, otherwise it will just match the *exact* path you specify.

Let me know if this resolves your problem!

**Comment by HerrStinson** [comment]
Thx @jorgenpt, that makes a whole lot of sense and works ;)
